import { Routes } from '@angular/router';
import { IndexComponent } from '../Pages/Landing/Home/index/index.component';
import { AboutUs1Component } from '../Pages/Landing/About/about-us-1/about-us-1.component';
import { FaqComponent } from '../Pages/Landing/OthersPages/faq/faq.component';
import { CompareComponent } from '../Pages/Landing/OthersPages/compare/compare.component';
import { Error404Component } from '../Pages/Landing/OthersPages/error404/error404.component';
import { AgencyDetailsComponent } from '../Pages/Landing/Agency/agency-details/agency-details.component';
import { AgentDetailsComponent } from '../Pages/Landing/Agent/agent-details/agent-details.component';
import { AgentComponent } from '../Pages/Landing/Agent/agent/agent.component';
import { AgencyComponent } from '../Pages/Landing/Agency/agency/agency.component';
import { ContactComponent } from '../Pages/Landing/OthersPages/contact/contact.component';
import { Pricing01Component } from '../Pages/Landing/Pricing/pricing-01/pricing-01.component';
import { Service01Component } from '../Pages/Landing/Service/service01/service01.component';
import { ServiceDetailsComponent } from '../Pages/Landing/Service/service-details/service-details.component';
import { Blog01Component } from '../Pages/Landing/Blog/blog-01/blog-01.component';
import { BlogDetailsComponent } from '../Pages/Landing/Blog/blog-details/blog-details.component';
import { ProjectDetails01Component } from '../Pages/Landing/Project/project-details-01/project-details-01.component';
import { Project01Component } from '../Pages/Landing/Project/project-01/project-01.component';
import { ListingDetails01Component } from '../Pages/Landing/Listing/listing-details-01/listing-details-01.component';
import { Listing04Component } from '../Pages/Landing/Listing/listing-04/listing-04.component';

export const MP_ROUTES: Routes = [
  { path: '', component: IndexComponent },
  { path: 'about_us_01', component: AboutUs1Component },
  { path: 'faq', component: FaqComponent },
  { path: 'compare', component: CompareComponent },
  { path: '404', component: Error404Component },
  { path: 'agency', component: AgencyComponent },
  { path: 'agency_details', component: AgencyDetailsComponent },
  { path: 'agent', component: AgentComponent },
  { path: 'agent_details/:id', component: AgentDetailsComponent },
  { path: 'agent_details', component: AgentDetailsComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'pricing_01', component: Pricing01Component },
  { path: 'service_01', component: Service01Component },
  { path: 'service_details', component: ServiceDetailsComponent },
  { path: 'blog_01', component: Blog01Component },
  { path: 'blog_details', component: BlogDetailsComponent },
  { path: 'project_01', component: Project01Component },
  { path: 'project_details_01', component: ProjectDetails01Component },
  { path: 'listing_details_01/:id', component: ListingDetails01Component },
  { path: 'listing_details_01', component: ListingDetails01Component },
  { path: 'listing_04', component: Listing04Component },
];
